'use strict';

import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import pkg from 'fs-extra';
const { emptyDir, readdir, copy, pathExists, outputFile, readFile } = pkg;

const __dirname = dirname(fileURLToPath(import.meta.url));

const AGENTS_SRC = join(__dirname, '..', 'agents');
const EXAMPLES_SRC = join(__dirname, '..', 'examples');

// Tool → agents destination folder (relative to project root)
const AGENTS_DEST = {
  'claude-code': 'agents',
  'cursor': '.cursor/skills',
  'copilot': '.github/agents',
};

// Tool → ignore file path (relative to project root)
// Only Cursor has an official ignore file. Claude Code uses .gitignore for context exclusions;
// Copilot exclusions are managed via GitHub.com repository settings.
const IGNORE_FILE = {
  'claude-code': null,
  'cursor': '.cursorignore',
  'copilot': null,
};

// Tool → MCP config path (relative to project root)
const MCP_CONFIG_PATH = {
  'claude-code': '.mcp.json',
  'cursor': '.cursor/mcp.json',
  'copilot': '.vscode/mcp.json',
};

const IGNORE_CONTENT = `# AI tool ignore file — generated by awesome-ai-setup
# These files are excluded from AI context. Add project-specific entries below.

# Secrets & credentials
.env
.env.*
!.env.example
*.pem
*.key
*.p12
*.pfx

# Dependencies
node_modules/
.pnp
.pnp.js
vendor/

# Build outputs
dist/
build/
out/
.next/
.nuxt/
.cache/
.output/

# Test coverage
coverage/
.nyc_output/

# Logs
*.log
npm-debug.log*
yarn-debug.log*

# OS & editor
.DS_Store
Thumbs.db
*.swp

# Large binary or generated assets
*.min.js
*.min.css
`;

// Read mcpServers/servers from a JSON file, return the servers object or null.
async function readMcpServers(filePath) {
  if (!await pathExists(filePath)) return null;
  try {
    const parsed = JSON.parse(await readFile(filePath, 'utf8'));
    const servers = parsed.servers || parsed.mcpServers;
    return (servers && Object.keys(servers).length > 0) ? servers : null;
  } catch {
    return null;
  }
}

// Gather the best available set of MCP servers to seed a new config file.
// Tries all known MCP config locations (project + user level, all tools) in priority order,
// skipping the destination file itself. Returns the first source that has servers, or null.
async function gatherKnownServers(cwd, excludePath) {
  const homedir = (await import('os')).homedir();
  const sources = [
    // Project-level (all tools)
    join(cwd, '.vscode', 'mcp.json'),   // Copilot
    join(cwd, '.cursor', 'mcp.json'),   // Cursor
    join(cwd, '.mcp.json'),             // Claude Code
    // User-level (all tools)
    join(homedir, '.cursor', 'mcp.json'),  // Cursor user-level
    join(homedir, '.mcp.json'),            // Claude Code user-level
    join(homedir, '.claude.json'),         // Claude Code user-level (alt)
    join(homedir, '.config', 'github-copilot', 'intellij', 'mcp.json'),  // Copilot user-level (JetBrains/Android Studio)
  ].filter(s => s !== excludePath);

  for (const src of sources) {
    const servers = await readMcpServers(src);
    if (servers) return { servers, source: src };
  }
  return null;
}

// Generate MCP config content for a tool, mirroring servers from the best available source.
async function mcpContentForTool(tool, cwd, destPath) {
  const key = tool === 'copilot' ? 'servers' : 'mcpServers';
  const found = await gatherKnownServers(cwd, destPath);
  const servers = found ? found.servers : {
    filesystem: { command: 'npx', args: ['-y', '@modelcontextprotocol/server-filesystem', '.'] },
  };
  return { content: JSON.stringify({ [key]: servers }, null, 2) + '\n', source: found ? found.source : null };
}

async function install(cwd, { tools = [], example, ignoreFiles, mcpStubs } = {}) {
  const installed = [];

  // Copy agents to each selected tool's expected location
  const agentDestDirs = [...new Set(tools.map(t => AGENTS_DEST[t]).filter(Boolean))];
  for (const destDir of agentDestDirs) {
    const agentsDest = join(cwd, destDir);
    await emptyDir(agentsDest);
    const srcFiles = await readdir(AGENTS_SRC);
    for (const file of srcFiles) {
      if (!file.endsWith('.md')) continue;
      if (destDir === AGENTS_DEST.cursor) {
        // Skills format: each agent gets its own folder with a SKILL.md file
        if (file === 'README.md') continue;
        const skillName = file.replace(/\.md$/, '');
        await copy(join(AGENTS_SRC, file), join(agentsDest, skillName, 'SKILL.md'));
      } else {
        await copy(join(AGENTS_SRC, file), join(agentsDest, file));
      }
    }
    const agentFiles = (await readdir(agentsDest)).filter(f => f !== 'README.md');
    const detail = destDir === AGENTS_DEST.cursor
      ? `${agentFiles.length} skills`
      : `${agentFiles.length} agents + README`;
    installed.push({ label: `${destDir}/`, detail });
  }

  // Tool-specific ignore files
  if (ignoreFiles) {
    for (const tool of tools) {
      const filePath = IGNORE_FILE[tool];
      if (!filePath) continue;
      const dest = join(cwd, filePath);
      if (!await pathExists(dest)) {
        await outputFile(dest, IGNORE_CONTENT);
        installed.push({ label: filePath, detail: `${tool} ignore file` });
      } else {
        installed.push({ label: filePath, detail: `${tool} ignore file (already exists — skipped)` });
      }
    }
  }

  // Tool-specific MCP config stubs
  if (mcpStubs) {
    for (const tool of tools) {
      const configPath = MCP_CONFIG_PATH[tool];
      if (!configPath) continue;
      const dest = join(cwd, configPath);
      if (!await pathExists(dest)) {
        const { content, source } = await mcpContentForTool(tool, cwd, dest);
        await outputFile(dest, content);
        const detail = source
          ? `${tool} MCP config (mirrored from ${source.replace(process.env.HOME, '~')})`
          : `${tool} MCP config stub (filesystem only — no existing config found to mirror)`;
        installed.push({ label: configPath, detail });
      } else {
        installed.push({ label: configPath, detail: `${tool} MCP config (already exists — skipped)` });
      }
    }
  }

  // Copy reference example if requested — skip (don't partial-merge) if it already exists
  if (example) {
    const exampleDest = join(cwd, '.ai', 'reference', example);
    if (await pathExists(exampleDest)) {
      installed.push({ label: `.ai/reference/${example}/`, detail: 'reference example (already exists — skipped)' });
    } else {
      await copy(join(EXAMPLES_SRC, example), exampleDest);
      installed.push({ label: `.ai/reference/${example}/`, detail: 'reference example' });
    }
  }

  return { installed };
}

export { install };
