'use strict';

const path = require('path');
const fse  = require('fs-extra');

const AGENTS_SRC  = path.join(__dirname, '..', 'agents');
const PRESETS_SRC = path.join(__dirname, '..', 'presets');

// Tool → ignore file path (relative to project root)
const IGNORE_FILE = {
  'claude-code': '.claudeignore',
  'cursor':      '.cursorignore',
  'copilot':     '.copilotignore',
};

// Tool → MCP config path (relative to project root)
const MCP_CONFIG_PATH = {
  'claude-code': '.mcp.json',
  'cursor':      '.cursor/mcp.json',
  'copilot':     '.vscode/mcp.json',
};

const IGNORE_CONTENT = `# AI tool ignore file — generated by awesome-ai-setup
# These files are excluded from AI context. Add project-specific entries below.

# Secrets & credentials
.env
.env.*
!.env.example
*.pem
*.key
*.p12
*.pfx

# Dependencies
node_modules/
.pnp
.pnp.js
vendor/

# Build outputs
dist/
build/
out/
.next/
.nuxt/
.cache/
.output/

# Test coverage
coverage/
.nyc_output/

# Logs
*.log
npm-debug.log*
yarn-debug.log*

# OS & editor
.DS_Store
Thumbs.db
*.swp

# Large binary or generated assets
*.min.js
*.min.css
`;

// VS Code uses "servers", Claude Code and Cursor use "mcpServers"
function mcpContent(tool) {
  const key = tool === 'copilot' ? 'servers' : 'mcpServers';
  return JSON.stringify({
    [key]: {
      github: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-github'],
        env: { GITHUB_PERSONAL_ACCESS_TOKEN: 'YOUR_TOKEN_HERE' },
      },
      filesystem: {
        command: 'npx',
        args: ['-y', '@modelcontextprotocol/server-filesystem', '.'],
      },
    },
  }, null, 2);
}

async function install(cwd, { tools = [], preset, ignoreFiles, mcpStubs } = {}) {
  const installed = [];

  // Copy agents/ — emptyDir first so renamed/removed files don't linger
  const agentsDest = path.join(cwd, 'agents');
  await fse.emptyDir(agentsDest);
  await fse.copy(AGENTS_SRC, agentsDest);
  const agentFiles = (await fse.readdir(agentsDest)).filter(f => f.endsWith('.md') && f !== 'README.md');
  installed.push({ label: 'agents/', detail: `${agentFiles.length} agents + README` });

  // Tool-specific ignore files
  if (ignoreFiles) {
    for (const tool of tools) {
      const filePath = IGNORE_FILE[tool];
      if (!filePath) continue;
      const dest = path.join(cwd, filePath);
      if (!await fse.pathExists(dest)) {
        await fse.outputFile(dest, IGNORE_CONTENT);
        installed.push({ label: filePath, detail: `${tool} ignore file` });
      } else {
        installed.push({ label: filePath, detail: `${tool} ignore file (already exists — skipped)` });
      }
    }
  }

  // Tool-specific MCP config stubs
  if (mcpStubs) {
    for (const tool of tools) {
      const configPath = MCP_CONFIG_PATH[tool];
      if (!configPath) continue;
      const dest = path.join(cwd, configPath);
      if (!await fse.pathExists(dest)) {
        await fse.outputFile(dest, mcpContent(tool) + '\n');
        installed.push({ label: configPath, detail: `${tool} MCP config stub` });
      } else {
        installed.push({ label: configPath, detail: `${tool} MCP config (already exists — skipped)` });
      }
    }
  }

  // Copy preset if requested — skip (don't partial-merge) if it already exists
  if (preset) {
    const presetDest = path.join(cwd, 'presets', preset);
    if (await fse.pathExists(presetDest)) {
      installed.push({ label: `presets/${preset}/`, detail: 'reference example (already exists — skipped)' });
    } else {
      await fse.copy(path.join(PRESETS_SRC, preset), presetDest);
      installed.push({ label: `presets/${preset}/`, detail: 'reference example' });
    }
  }

  return { installed };
}

module.exports = { install };
