'use strict';

import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import pkg from 'fs-extra';
const { emptyDir, readdir, copy, pathExists, outputFile } = pkg;

const __dirname = dirname(fileURLToPath(import.meta.url));

const AGENTS_SRC = join(__dirname, '..', 'agents');
const EXAMPLES_SRC = join(__dirname, '..', 'examples');

// Tool → agents destination folder (relative to project root)
const AGENTS_DEST = {
  'claude-code': 'agents',
  'cursor': '.cursor/commands',
  'copilot': '.github/agents',
};

// Tool → ignore file path (relative to project root)
const IGNORE_FILE = {
  'claude-code': '.claudeignore',
  'cursor': '.cursorignore',
  'copilot': '.copilotignore',
};

// Tool → MCP config path (relative to project root)
const MCP_CONFIG_PATH = {
  'claude-code': '.mcp.json',
  'cursor': '.cursor/mcp.json',
  'copilot': '.vscode/mcp.json',
};

const IGNORE_CONTENT = `# AI tool ignore file — generated by awesome-ai-setup
# These files are excluded from AI context. Add project-specific entries below.

# Secrets & credentials
.env
.env.*
!.env.example
*.pem
*.key
*.p12
*.pfx

# Dependencies
node_modules/
.pnp
.pnp.js
vendor/

# Build outputs
dist/
build/
out/
.next/
.nuxt/
.cache/
.output/

# Test coverage
coverage/
.nyc_output/

# Logs
*.log
npm-debug.log*
yarn-debug.log*

# OS & editor
.DS_Store
Thumbs.db
*.swp

# Large binary or generated assets
*.min.js
*.min.css
`;

// VS Code uses "servers", Claude Code and Cursor use "mcpServers"
function mcpContent(tool) {
  const key = tool === 'copilot' ? 'servers' : 'mcpServers';
  return `{
  "${key}": {
    // Uncomment and add your token to enable GitHub MCP server
    // "github": {
    //   "command": "npx",
    //   "args": ["-y", "@modelcontextprotocol/server-github"],
    //   "env": { "GITHUB_PERSONAL_ACCESS_TOKEN": "YOUR_TOKEN_HERE" }
    // },
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "."]
    }
  }
}
`;
}

async function install(cwd, { tools = [], example, ignoreFiles, mcpStubs } = {}) {
  const installed = [];

  // Copy agents to each selected tool's expected location
  const agentDestDirs = [...new Set(tools.map(t => AGENTS_DEST[t]).filter(Boolean))];
  for (const destDir of agentDestDirs) {
    const agentsDest = join(cwd, destDir);
    await emptyDir(agentsDest);
    const srcFiles = await readdir(AGENTS_SRC);
    for (const file of srcFiles) {
      if (!file.endsWith('.md')) continue;
      // Copilot requires .agent.md extension; README stays as-is
      const destFile = (destDir === AGENTS_DEST.copilot && file !== 'README.md')
        ? file.replace(/\.md$/, '.agent.md')
        : file;
      await copy(join(AGENTS_SRC, file), join(agentsDest, destFile));
    }
    const agentFiles = (await readdir(agentsDest)).filter(f => f !== 'README.md');
    installed.push({ label: `${destDir}/`, detail: `${agentFiles.length} agents + README` });
  }

  // Tool-specific ignore files
  if (ignoreFiles) {
    for (const tool of tools) {
      const filePath = IGNORE_FILE[tool];
      if (!filePath) continue;
      const dest = join(cwd, filePath);
      if (!await pathExists(dest)) {
        await outputFile(dest, IGNORE_CONTENT);
        installed.push({ label: filePath, detail: `${tool} ignore file` });
      } else {
        installed.push({ label: filePath, detail: `${tool} ignore file (already exists — skipped)` });
      }
    }
  }

  // Tool-specific MCP config stubs
  if (mcpStubs) {
    for (const tool of tools) {
      const configPath = MCP_CONFIG_PATH[tool];
      if (!configPath) continue;
      const dest = join(cwd, configPath);
      if (!await pathExists(dest)) {
        await outputFile(dest, mcpContent(tool) + '\n');
        installed.push({ label: configPath, detail: `${tool} MCP config stub` });
      } else {
        installed.push({ label: configPath, detail: `${tool} MCP config (already exists — skipped)` });
      }
    }
  }

  // Copy reference example if requested — skip (don't partial-merge) if it already exists
  if (example) {
    const exampleDest = path.join(cwd, '.ai', 'reference', example);
    if (await fse.pathExists(exampleDest)) {
      installed.push({ label: `.ai/reference/${example}/`, detail: 'reference example (already exists — skipped)' });
    } else {
      await fse.copy(path.join(EXAMPLES_SRC, example), exampleDest);
      installed.push({ label: `.ai/reference/${example}/`, detail: 'reference example' });
    }
  }

  return { installed };
}

export { install };
